swagger: "2.0"
info:
  description: "This is a sample server Petstore server."
  version: "1.0.0"
  title: "Assessment Checker"
host: "localhost:3000"
basePath: /
consumes:
  - application/json
produces:
  - application/json
paths:
  
   /teacher/leaderBoard:
    get:
      tags:
      - "pet"
      summary: "Finds Pets by status"
      description: "Multiple status values can be provided with comma separated strings"
      produces:
      - "application/json"
      
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                _id:
                  type : "string"
                total_score:
                  type : "integer"
                spelling_score:
                  type : "integer"
                grammar_score:
                  type : "integer"
        400:
          description: "Invalid status value"